pipeline {
    agent {
    docker {
        image 'docker:24.0.2-dind'
        args '--privileged -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    
    environment {
        NODE_ENV = 'development'
    }

    stages {
        stage('Checkout') {
            steps {
                echo "📥 Haciendo checkout del repositorio..."
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                echo "📦 Instalando dependencias..."
                sh 'apk add --no-cache nodejs npm git && npm install'
            }
        }

        stage('Lint') {
            steps {
                echo "🔍 Corriendo Linter..."
                sh 'npm run lint || true'
            }
        }

        stage('Run Tests') {
            steps {
                echo "🧪 Ejecutando tests..."
                sh 'npm test'
            }
        }

        stage('Build Frontend') {
            steps {
                echo "🏗️ Construyendo frontend..."
                sh 'npm run build'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "🐳 Construyendo imagen Docker del frontend..."
                sh 'docker build -t frontend-ci-image .'
            }
        }
    }

    post {
        success {
            echo '✅ Frontend CI completado con éxito!'
        }
        failure {
            echo '❌ Frontend CI FALLÓ'
        }
    }
}
