services:
  db:
    image: postgres:16
    container_name: nocountry-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mvp
    ports:
      - '5432:5432'
    volumes:
      - nocountry_pgdata:/var/lib/postgresql/data

volumes:
  nocountry_pgdata:
